### ISSUE TITLE
Good start, needs further details

### ISSUE THREAD

**Issue by hackers-test** [floodowen/climatetool#1]
This is good start, but needs to be expanded a bit further before I can approve it for your project.

### Goal
The project goal sounds good. It seems this may be well suited for an interactive web app, perhaps something you could develop using the `streamlit` Python package.

### Code
Here I'm looking for you to envision what type of packages you will use, and what type of modules or classes you will write. As you said, folium may work well for creating chloropleth maps to show statistics by state. I think that's a good idea. But what programs will you use to get the data, load the data, and analyze the data? Here pandas seems like a very likely choice. 

Simply loading data and visualizing it may end up being relatively easy. If so, you can think about how to expand on this. What other types of analyses could you perform? Perhaps you could implement clustering analyses using scikit-learn to group states by how similar their healthcare issues and plotting these results on a map. Or, depending on how health data is structured, you could implement more complex analyses. If the data is largely text-based instead of numeric, then you could use something like natural language processing to decompose text into numeric values before you analyses is. Here you could use a program like spacy. 

### Data
Where will the data come from? Have you found a suitable healthcare database yet? This is the more important starting point. Once you find it, how will you access it? If it is enormous then you may want to use an API to access it. If it is reasonably sized then maybe you can just download it in CSV format.

### User interaction
How will the use specify a state? Using a command line tool, using a web interface, using the Python API, all three?

### Planning your code
Once you decide more about some of the questions above you should begin to plan the structure of your code. What major tasks are involved, and how can you write a class to perform each of these? Start by writing psuedocode to break it down into parts. You could expand on the example below, or use a structure quite different depending on what you decide. I think your first biggest task is to explore more to find the right database and libraries that you want to use to analyze it.

```python
class GetData:
    "fetches data for some specific query for every state"

class Analyze:
    "performs a clustering analysis to group states by similarity in data X,Y,Z"

class Visualize:
    "produces chloropleth maps with values for each state in the US using folium"
```

**Comment by eaton-lab** [comment]
The updated proposal plan looks great. Approved. You can go ahead and work on your formal proposal.
